Add test homepage
- Works except for error upon send
sqlalchemy.exc.ProgrammingError
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "pdfform" does not exist
LINE 1: INSERT INTO pdfform (original_pdf, original_pdf_title, fdf_m...